# Site settings
title:          Mao FENG
description:    "My personal blog to record learnings and insights"
url:            "https://maofeng1709.github.io"

# Author
author:
  name:         Mao FENG
  email:        maofeng1709@gmail.com
  github:       https://github.com/maofeng1709
  linkedin:     https://www.linkedin.com/in/mao-feng-ba975a12b/

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:categories/:year-:month-:day/:title


#pagination
paginate:       1
paginate_path: "/posts/page:num/"


linenos: true

